-- ======================================================
-- LIFE LINE HOSPITAL AMBIKAPUR - SUPABASE POSTGRES SCHEMA
-- Project Reference: wduxusyodnfqnhtdtltl
-- ======================================================

-- 1. Appointments Table
CREATE TABLE IF NOT EXISTS public.appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id TEXT UNIQUE NOT NULL,
    patient_name TEXT NOT NULL,
    patient_phone TEXT NOT NULL,
    department TEXT NOT NULL,
    doctor_name TEXT NOT NULL,
    appointment_date DATE NOT NULL,
    preferred_time TEXT DEFAULT 'Morning 10-12 PM',
    status TEXT DEFAULT 'Pending',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Doctors Table
CREATE TABLE IF NOT EXISTS public.doctors (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    specialty_id TEXT NOT NULL,
    specialty_name TEXT NOT NULL,
    qualifications TEXT,
    experience TEXT,
    opd_time TEXT,
    opd_days TEXT DEFAULT 'Mon-Sat',
    fee NUMERIC(10,2) DEFAULT 500.00,
    bio TEXT,
    image TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Departments Table
CREATE TABLE IF NOT EXISTS public.departments (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    icon TEXT,
    short_desc TEXT,
    full_description TEXT,
    key_treatments TEXT,
    icon_bg TEXT DEFAULT '#e6f7f5',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Facilities Table
CREATE TABLE IF NOT EXISTS public.facilities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT NOT NULL,
    icon TEXT,
    image TEXT,
    category TEXT DEFAULT 'Critical Care',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Blogs Table
CREATE TABLE IF NOT EXISTS public.blogs (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    author TEXT DEFAULT 'Life Line Medical Editorial',
    date_str TEXT,
    read_time TEXT DEFAULT '6 min read',
    excerpt TEXT,
    content TEXT NOT NULL,
    image TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Gallery Table
CREATE TABLE IF NOT EXISTS public.gallery (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    category TEXT DEFAULT 'Facilities',
    image TEXT NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Testimonials Table
CREATE TABLE IF NOT EXISTS public.testimonials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_name TEXT NOT NULL,
    location TEXT DEFAULT 'Ambikapur',
    treatment TEXT,
    comment TEXT NOT NULL,
    rating INT DEFAULT 5,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Contact Inquiries Table
CREATE TABLE IF NOT EXISTS public.contact_inquiries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inquiry_id TEXT UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    query_type TEXT DEFAULT 'General OPD Inquiry',
    message TEXT,
    status TEXT DEFAULT 'New',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Hospital Settings Table
CREATE TABLE IF NOT EXISTS public.hospital_settings (
    setting_key TEXT PRIMARY KEY,
    setting_value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) & Public Policies
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.doctors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.departments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.facilities ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blogs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.gallery ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_inquiries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hospital_settings ENABLE ROW LEVEL SECURITY;

-- Create Permissive RLS Policies for Anon API Access
DROP POLICY IF EXISTS "Allow public read all" ON public.appointments;
CREATE POLICY "Allow public read all" ON public.appointments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert appointments" ON public.appointments;
CREATE POLICY "Allow public insert appointments" ON public.appointments FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read doctors" ON public.doctors;
CREATE POLICY "Allow public read doctors" ON public.doctors FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public all doctors" ON public.doctors;
CREATE POLICY "Allow public all doctors" ON public.doctors FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read departments" ON public.departments;
CREATE POLICY "Allow public read departments" ON public.departments FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public all departments" ON public.departments;
CREATE POLICY "Allow public all departments" ON public.departments FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read facilities" ON public.facilities;
CREATE POLICY "Allow public read facilities" ON public.facilities FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public all facilities" ON public.facilities;
CREATE POLICY "Allow public all facilities" ON public.facilities FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read blogs" ON public.blogs;
CREATE POLICY "Allow public read blogs" ON public.blogs FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public all blogs" ON public.blogs;
CREATE POLICY "Allow public all blogs" ON public.blogs FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read gallery" ON public.gallery;
CREATE POLICY "Allow public read gallery" ON public.gallery FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public all gallery" ON public.gallery;
CREATE POLICY "Allow public all gallery" ON public.gallery FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read testimonials" ON public.testimonials;
CREATE POLICY "Allow public read testimonials" ON public.testimonials FOR SELECT USING (true);
DROP POLICY IF EXISTS "Allow public all testimonials" ON public.testimonials;
CREATE POLICY "Allow public all testimonials" ON public.testimonials FOR ALL USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public read contact_inquiries" ON public.contact_inquiries;
CREATE POLICY "Allow public read contact_inquiries" ON public.contact_inquiries FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow public insert contact_inquiries" ON public.contact_inquiries;
CREATE POLICY "Allow public insert contact_inquiries" ON public.contact_inquiries FOR INSERT WITH CHECK (true);

-- Seed Initial Doctors
INSERT INTO public.doctors (id, name, specialty_id, specialty_name, qualifications, experience, opd_time, fee, image) VALUES
('doc-1', 'Dr. S. K. Sharma', 'cardiology', 'Cardiology', 'MD, DM (Cardiology), FACC', '18+ Years', '10:00 AM - 04:00 PM', 600.00, '/assets/images/doctors_team.png'),
('doc-2', 'Dr. Ananya Verma', 'gynecology', 'Obstetrics & Gynecology', 'MS (Obs & Gynae), DNB', '14+ Years', '10:00 AM - 02:00 PM', 500.00, '/assets/images/doctors_team.png'),
('doc-3', 'Dr. Rajesh Patel', 'orthopedics', 'Orthopedics & Joint Replacement', 'MS (Ortho), Fellowship in Joint Replacement', '15+ Years', '11:00 AM - 05:00 PM', 500.00, '/assets/images/doctors_team.png'),
('doc-4', 'Dr. Meena Gupta', 'pediatrics', 'Pediatrics & Neonatology', 'MD (Pediatrics), DCH', '12+ Years', '09:30 AM - 03:00 PM', 450.00, '/assets/images/doctors_team.png'),
('doc-5', 'Dr. Vikas Singh', 'neurology', 'Neurology & Neurosurgery', 'DM (Neurology), MBBS', '16+ Years', '12:00 PM - 06:00 PM', 700.00, '/assets/images/doctors_team.png')
ON CONFLICT (id) DO NOTHING;
